### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by VladPerervenko** [yonicd/bplyr#5]
`> data.frame(package = c('rlang','dplyr','tidyr'),
+            stringsAsFactors = FALSE)%>%
+     bplyr::b_group_by(package)%>%
+     bplyr::b_mutate(version = as.character(packageVersion(package)))%>%
+     knitr::kable()

|package |version |
|:-------|:-------|
|dplyr   |0.8.4   |
|rlang   |0.4.4   |
|tidyr   |1.0.2   |
Предупреждение:
`quo_expr()` is deprecated as of rlang 0.2.0.
Please use `quo_squash()` instead.
This warning is displayed once per session`

**Comment by yonicd** [comment]
thanks. will update

**Comment by yonicd** [comment]
https://github.com/yonicd/bplyr/commit/553f658e10cf50f32bdaeaed0b0117df8c5f0952
